import React, { useState, useEffect, useRef } from 'react';
import { GeminiService } from '../services/geminiService';
import { db } from '../services/dbService';
import { ChatMessage, DocumentRecord, Classification, RecordStatus, UserRole, UserProfile } from '../types';
import { Send, Cpu, Zap, FileText, UploadCloud, Lock } from 'lucide-react';
import KnowledgeGraph from './KnowledgeGraph';

const KnowledgeBase: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'chat' | 'documents'>('chat');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [mode, setMode] = useState<'FAST' | 'THINKING'>('FAST');
  const [isProcessing, setIsProcessing] = useState(false);
  const [records, setRecords] = useState<DocumentRecord[]>([]);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  
  // File upload simulation state
  const fileInputRef = useRef<HTMLInputElement>(null);
  
  const [user, setUser] = useState<UserProfile | null>(null);

  useEffect(() => {
    const init = async () => {
        const u = await db.getUser();
        setUser(u);
        const r = await db.getRecords();
        setRecords(r);
    };
    init();

    // Initial welcome message
    setMessages([{
      role: 'model',
      content: 'Hello. I am Rekama, your Information Governance sentinel. How can I assist you with your data today?',
      timestamp: Date.now()
    }]);
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const refreshRecords = async () => {
      const r = await db.getRecords();
      setRecords(r);
  };

  const handleSendMessage = async () => {
    if (!input.trim() || isProcessing) return;

    const userMsg: ChatMessage = { role: 'user', content: input, timestamp: Date.now() };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsProcessing(true);

    // Context from vector store (mocked by simply listing document titles for now)
    const context = records.map(r => `Document: ${r.title} (${r.classification})`).join('\n');
    const history = messages.slice(-5).map(m => `${m.role}: ${m.content}`);
    
    const responseText = await GeminiService.chat(input, [`System: You have access to these documents:\n${context}`, ...history], mode);

    const modelMsg: ChatMessage = { 
        role: 'model', 
        content: responseText, 
        timestamp: Date.now(),
        isThinking: mode === 'THINKING'
    };
    
    setMessages(prev => [...prev, modelMsg]);
    setIsProcessing(false);
  };

  if(!user) return null;
  const canUpload = user.role === UserRole.Admin || user.role === UserRole.Officer;

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
      if(!canUpload) return;

      if (e.target.files && e.target.files.length > 0) {
          const file = e.target.files[0];
          const type = file.name.endsWith('.docx') ? 'DOCX' : 'PDF'; // simple mock check
          
          const newRec: DocumentRecord = {
              id: `rec_${Date.now()}`,
              title: file.name,
              type: type,
              classification: Classification.Internal,
              status: RecordStatus.Active,
              riskScore: 0, // Pending scan
              source: 'Local',
              uploadedAt: new Date().toISOString(),
              legalHold: false,
              checksum: '', // Will be generated by DB
              version: 1,
              custodian: user.name,
              format: file.type || (type === 'PDF' ? 'application/pdf' : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
          };
          
          await db.addRecord(newRec);
          await db.addLog({
            id: `log_${Date.now()}`,
            timestamp: new Date().toISOString(),
            user: user.email,
            action: 'UPLOAD_DOCUMENT',
            resource: file.name,
            severity: 'Low'
          });
          
          refreshRecords();
          alert("Document uploaded and indexed successfully.");
      }
  };

  return (
    <div className="flex h-full gap-6">
      {/* Left Panel: Chat or Docs List */}
      <div className="flex-1 flex flex-col bg-slate-800 rounded-xl border border-slate-700 shadow-lg overflow-hidden">
        {/* Header Tabs */}
        <div className="flex border-b border-slate-700">
          <button
            onClick={() => setActiveTab('chat')}
            className={`flex-1 py-3 text-sm font-medium transition-colors ${activeTab === 'chat' ? 'bg-slate-700 text-white border-b-2 border-blue-500' : 'text-slate-400 hover:text-slate-200'}`}
          >
            Assistant
          </button>
          <button
            onClick={() => { setActiveTab('documents'); refreshRecords(); }}
            className={`flex-1 py-3 text-sm font-medium transition-colors ${activeTab === 'documents' ? 'bg-slate-700 text-white border-b-2 border-blue-500' : 'text-slate-400 hover:text-slate-200'}`}
          >
            Vector Store ({records.length})
          </button>
        </div>

        {activeTab === 'chat' ? (
          <div className="flex-1 flex flex-col relative">
            {/* Mode Toggles */}
            <div className="absolute top-4 right-4 flex bg-slate-900 rounded-lg p-1 border border-slate-700 z-10">
              <button
                onClick={() => setMode('FAST')}
                className={`px-3 py-1 rounded text-xs flex items-center gap-1 transition-all ${mode === 'FAST' ? 'bg-blue-600 text-white' : 'text-slate-400 hover:text-white'}`}
              >
                <Zap size={12} /> Fast
              </button>
              <button
                onClick={() => setMode('THINKING')}
                className={`px-3 py-1 rounded text-xs flex items-center gap-1 transition-all ${mode === 'THINKING' ? 'bg-purple-600 text-white' : 'text-slate-400 hover:text-white'}`}
              >
                <Cpu size={12} /> Thinking
              </button>
            </div>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4 pt-12">
              {messages.map((msg, idx) => (
                <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-[80%] rounded-xl p-3 text-sm leading-relaxed ${
                    msg.role === 'user' 
                      ? 'bg-blue-600 text-white rounded-br-none' 
                      : 'bg-slate-700 text-slate-200 rounded-bl-none border border-slate-600'
                  }`}>
                     {msg.isThinking && <div className="text-xs text-purple-300 font-mono mb-1 flex items-center gap-1"><Cpu size={10}/> Reasoning Chain Active</div>}
                     <div className="whitespace-pre-wrap">{msg.content}</div>
                  </div>
                </div>
              ))}
              {isProcessing && (
                <div className="flex justify-start">
                  <div className="bg-slate-700 rounded-xl p-3 rounded-bl-none flex items-center gap-2">
                    <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                    <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                    <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                  </div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Input */}
            <div className="p-4 bg-slate-900 border-t border-slate-700">
              <div className="flex items-center gap-2">
                <input
                  type="text"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                  placeholder={`Ask about your data (${mode === 'FAST' ? 'Flash Lite' : 'Pro Reasoning'})...`}
                  className="flex-1 bg-slate-800 border border-slate-700 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-blue-500"
                />
                <button
                  onClick={handleSendMessage}
                  disabled={!input.trim() || isProcessing}
                  className="p-2 bg-blue-600 rounded-lg text-white hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Send size={18} />
                </button>
              </div>
            </div>
          </div>
        ) : (
          <div className="flex-1 overflow-y-auto p-4">
             {canUpload ? (
                 <>
                    <input 
                        type="file" 
                        ref={fileInputRef} 
                        className="hidden" 
                        accept=".pdf,.docx,.txt"
                        onChange={handleFileUpload}
                    />
                    <div 
                        onClick={() => fileInputRef.current?.click()}
                        className="border-2 border-dashed border-slate-700 rounded-xl p-8 flex flex-col items-center justify-center text-slate-500 mb-6 hover:border-blue-500 hover:text-blue-400 transition-colors cursor-pointer bg-slate-900/50"
                    >
                        <UploadCloud size={48} className="mb-2" />
                        <p>Click to Index New Documents (PDF, DOCX)</p>
                    </div>
                 </>
             ) : (
                 <div className="border-2 border-dashed border-slate-800 rounded-xl p-8 flex flex-col items-center justify-center text-slate-600 mb-6 bg-slate-900/30">
                    <Lock size={32} className="mb-2 opacity-50" />
                    <p>Upload restricted to Officers and Admins</p>
                 </div>
             )}

             <div className="flex items-center justify-between mb-3">
                 <h3 className="text-slate-300 font-semibold">Indexed Records</h3>
                 <span className="text-xs text-slate-500">{records.length} items</span>
             </div>
             <div className="space-y-2">
                {records.map(rec => (
                    <div key={rec.id} className="flex items-center justify-between p-3 bg-slate-900 rounded border border-slate-700">
                        <div className="flex items-center gap-3">
                            <FileText size={18} className="text-blue-400" />
                            <div>
                                <p className="text-sm font-medium text-slate-200">{rec.title}</p>
                                <p className="text-xs text-slate-500">{rec.classification} • {rec.type}</p>
                            </div>
                        </div>
                        <span className={`text-xs px-2 py-1 rounded bg-slate-800 border ${rec.status === 'Active' ? 'text-green-400 border-green-900' : 'text-slate-400 border-slate-700'}`}>
                            {rec.status}
                        </span>
                    </div>
                ))}
             </div>
          </div>
        )}
      </div>

      {/* Right Panel: Visualization */}
      <div className="w-[400px] hidden xl:flex flex-col gap-6">
        <KnowledgeGraph />
        
        <div className="bg-slate-800 rounded-xl border border-slate-700 p-4 shadow-lg flex-1">
            <h3 className="text-slate-300 font-semibold mb-4">RAG Status</h3>
            <div className="space-y-4">
                <div className="flex justify-between items-center text-sm">
                    <span className="text-slate-400">Embedding Model</span>
                    <span className="text-blue-300">text-embedding-004</span>
                </div>
                <div className="flex justify-between items-center text-sm">
                    <span className="text-slate-400">Vector Index</span>
                    <span className="text-green-400">Online</span>
                </div>
                <div className="flex justify-between items-center text-sm">
                    <span className="text-slate-400">Chunk Strategy</span>
                    <span className="text-slate-300">Sliding Window (512/64)</span>
                </div>
                <div className="h-px bg-slate-700 my-2"></div>
                <div className="p-3 bg-slate-900/50 rounded border border-slate-700/50">
                    <p className="text-xs text-slate-400 mb-1">Last Query Vector</p>
                    <div className="flex gap-1">
                        {[...Array(20)].map((_,i) => (
                            <div key={i} className="w-1 h-4 bg-blue-500/40 rounded-sm" style={{opacity: Math.random()}}></div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};

export default KnowledgeBase;