import React, { useState, useEffect } from 'react';
import { db } from '../services/dbService';
import { DocumentRecord, Classification, RecordStatus, UserRole, UserProfile, RetentionSchedule } from '../types';
import { Trash2, Plus, FileText, Scale, Archive, CalendarClock, Shield, XCircle, Search, Hash, GitCommit } from 'lucide-react';

const RecordsRegistry: React.FC = () => {
  const [records, setRecords] = useState<DocumentRecord[]>([]);
  const [schedules, setSchedules] = useState<RetentionSchedule[]>([]);
  const [user, setUser] = useState<UserProfile | null>(null);
  
  // Filters
  const [filterHold, setFilterHold] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');

  // Add/Edit State
  const [showAddModal, setShowAddModal] = useState(false);
  const [newRecordTitle, setNewRecordTitle] = useState('');
  const [newRecordType, setNewRecordType] = useState<'PDF' | 'DOCX'>('PDF');
  const [newRecordClass, setNewRecordClass] = useState<Classification>(Classification.Internal);
  const [newRecordSource, setNewRecordSource] = useState('Local');
  const [newRecordSchedule, setNewRecordSchedule] = useState('');

  useEffect(() => {
    const init = async () => {
        const u = await db.getUser();
        setUser(u);
        refreshData();
    };
    init();
  }, []);

  const refreshData = async () => {
    const r = await db.getRecords();
    const s = await db.getSchedules();
    setRecords(r);
    setSchedules(s);
  };

  if (!user) return null;
  const canEdit = user.role === UserRole.Admin || user.role === UserRole.Officer;
  const canDelete = user.role === UserRole.Admin;

  // Actions
  const toggleLegalHold = async (rec: DocumentRecord) => {
      if(!canEdit) return;
      await db.updateRecord(rec.id, { legalHold: !rec.legalHold });
      await db.addLog({
          id: `log_${Date.now()}`,
          timestamp: new Date().toISOString(),
          user: user.email,
          action: rec.legalHold ? 'REMOVE_LEGAL_HOLD' : 'APPLY_LEGAL_HOLD',
          resource: rec.id,
          severity: 'High'
      });
      refreshData();
  };

  const handleDelete = async (rec: DocumentRecord) => {
    if (rec.legalHold) {
        alert("Cannot destroy record under Legal Hold.");
        return;
    }
    if (confirm(`Confirm secure destruction of ${rec.title}? \n\nThis action will generate a formal Certificate of Destruction (ISO 15489).`)) {
        await db.deleteRecord(rec.id, user.email);
        refreshData();
    }
  };

  const handleAddRecord = async () => {
      if(!newRecordTitle) return;
      
      let disposalDate = undefined;
      const selectedSchedule = schedules.find(s => s.id === newRecordSchedule);
      if (selectedSchedule) {
          const d = new Date();
          d.setFullYear(d.getFullYear() + selectedSchedule.retentionYears);
          disposalDate = d.toISOString();
      }

      const newRec: DocumentRecord = {
          id: `rec_${Date.now()}`,
          title: newRecordTitle,
          type: newRecordType,
          classification: newRecordClass,
          status: RecordStatus.Active,
          riskScore: 0,
          source: newRecordSource,
          uploadedAt: new Date().toISOString(),
          legalHold: false,
          retentionScheduleId: newRecordSchedule,
          disposalDate,
          checksum: '', // Will be generated by DB
          version: 1,
          custodian: user.name,
          format: newRecordType === 'PDF' ? 'application/pdf' : 'application/docx'
      };
      await db.addRecord(newRec);
      refreshData();
      setShowAddModal(false);
      setNewRecordTitle('');
  };

  const filteredRecords = records.filter(r => {
      const matchesSearch = r.title.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesHold = filterHold ? r.legalHold : true;
      return matchesSearch && matchesHold;
  });

  return (
    <div className="h-full flex flex-col gap-6 animate-fade-in">
      <div className="flex justify-between items-center">
        <div>
            <h2 className="text-xl font-bold text-white">Master Inventory & Sentencing</h2>
            <p className="text-slate-400 text-sm">Manage lifecycle, integrity, and ISO compliant disposition.</p>
        </div>
        <div className="flex gap-3">
             <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={16} />
                <input 
                    type="text" 
                    placeholder="Search inventory..." 
                    value={searchTerm}
                    onChange={e => setSearchTerm(e.target.value)}
                    className="bg-slate-800 border border-slate-700 rounded-lg pl-9 pr-4 py-2 text-sm text-white focus:outline-none focus:border-blue-500"
                />
            </div>
            <button 
                onClick={() => setFilterHold(!filterHold)}
                className={`px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 border ${filterHold ? 'bg-red-500/10 text-red-400 border-red-500/30' : 'bg-slate-800 text-slate-400 border-slate-700 hover:text-white'}`}
            >
                <Scale size={16} /> {filterHold ? 'Legal Hold Active' : 'Filter Holds'}
            </button>
            {canEdit && (
                <button 
                    onClick={() => setShowAddModal(true)}
                    className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg transition-colors"
                >
                    <Plus size={18} /> Register Record
                </button>
            )}
        </div>
      </div>

      <div className="bg-slate-800 rounded-xl border border-slate-700 shadow-lg overflow-hidden flex-1 flex flex-col">
        <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-slate-400">
                <thead className="bg-slate-900 text-slate-200 uppercase font-medium">
                    <tr>
                        <th className="px-6 py-4">Record Identity</th>
                        <th className="px-6 py-4">Authority (Sentence)</th>
                        <th className="px-6 py-4">Integrity (ISO 16175)</th>
                        <th className="px-6 py-4">Status</th>
                        <th className="px-6 py-4">Legal Hold</th>
                        {canDelete && <th className="px-6 py-4 text-right">Actions</th>}
                    </tr>
                </thead>
                <tbody className="divide-y divide-slate-700">
                    {filteredRecords.map(record => {
                        const schedule = schedules.find(s => s.id === record.retentionScheduleId);
                        const isDisposalDue = record.disposalDate && new Date(record.disposalDate) < new Date();

                        return (
                        <tr key={record.id} className="hover:bg-slate-700/50 transition-colors">
                            <td className="px-6 py-4">
                                <div className="flex items-center gap-3">
                                    <FileText className="text-blue-400" size={18} />
                                    <div>
                                        <div className="text-white font-medium">{record.title}</div>
                                        <div className="text-xs text-slate-500 flex gap-2">
                                            <span>{record.type}</span>
                                            <span>•</span>
                                            <span className="flex items-center gap-1"><GitCommit size={10} /> v{record.version || 1}.0</span>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td className="px-6 py-4">
                                {schedule ? (
                                    <div className="flex flex-col">
                                        <span className="text-slate-200 font-mono text-xs">{schedule.code}</span>
                                        <div className={`text-xs flex items-center gap-1 mt-0.5 ${isDisposalDue ? 'text-red-400 font-bold' : 'text-slate-500'}`}>
                                            <CalendarClock size={10} />
                                            {record.disposalDate ? new Date(record.disposalDate).toLocaleDateString() : 'N/A'}
                                        </div>
                                    </div>
                                ) : (
                                    <span className="text-xs text-orange-400 bg-orange-500/10 px-2 py-1 rounded">Unsentenced</span>
                                )}
                            </td>
                            <td className="px-6 py-4">
                                <div className="flex flex-col gap-1">
                                    <div className="flex items-center gap-1 text-xs text-slate-300" title={record.checksum}>
                                        <Hash size={12} className="text-purple-400" />
                                        <span className="font-mono">{record.checksum ? record.checksum.substring(0, 8) + '...' : 'Calculating'}</span>
                                    </div>
                                    <span className="text-[10px] text-slate-600">SHA-256 Verified</span>
                                </div>
                            </td>
                            <td className="px-6 py-4">
                                <span className={`px-2 py-1 rounded text-xs font-medium border ${
                                    record.classification === Classification.Public ? 'bg-green-500/10 text-green-400 border-green-500/20' :
                                    record.classification === Classification.Restricted ? 'bg-red-500/10 text-red-400 border-red-500/20' :
                                    'bg-blue-500/10 text-blue-400 border-blue-500/20'
                                }`}>
                                    {record.classification}
                                </span>
                            </td>
                            <td className="px-6 py-4">
                                <button 
                                    onClick={() => toggleLegalHold(record)}
                                    className={`flex items-center gap-1 text-xs px-2 py-1 rounded border transition-colors ${
                                        record.legalHold 
                                        ? 'bg-red-500 text-white border-red-500' 
                                        : 'bg-slate-800 text-slate-500 border-slate-600 hover:border-slate-400'
                                    }`}
                                >
                                    <Scale size={12} />
                                    {record.legalHold ? 'Active Hold' : 'No Hold'}
                                </button>
                            </td>
                            {canDelete && (
                                <td className="px-6 py-4 text-right">
                                    <button 
                                        onClick={() => handleDelete(record)}
                                        disabled={record.legalHold}
                                        className={`p-1.5 rounded transition-colors ${
                                            record.legalHold 
                                            ? 'text-slate-600 cursor-not-allowed' 
                                            : 'hover:bg-red-500/20 text-slate-400 hover:text-red-400'
                                        }`}
                                        title={record.legalHold ? "Cannot destroy: Legal Hold Active" : "Secure Disposition"}
                                    >
                                        <Trash2 size={16} />
                                    </button>
                                </td>
                            )}
                        </tr>
                    )})}
                    {filteredRecords.length === 0 && (
                        <tr>
                            <td colSpan={6} className="px-6 py-8 text-center text-slate-500">
                                No records found matching criteria.
                            </td>
                        </tr>
                    )}
                </tbody>
            </table>
        </div>
      </div>

      {/* Add Modal */}
      {showAddModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
            <div className="bg-slate-800 rounded-xl border border-slate-700 p-6 w-full max-w-md shadow-2xl">
                <div className="flex justify-between items-center mb-4">
                     <h3 className="text-xl font-bold text-white">Register New Record</h3>
                     <button onClick={() => setShowAddModal(false)}><XCircle className="text-slate-400 hover:text-white" /></button>
                </div>
                <div className="space-y-4">
                    <div>
                        <label className="block text-sm text-slate-400 mb-1">Record Title</label>
                        <input 
                            type="text" 
                            className="w-full bg-slate-900 border border-slate-700 rounded p-2 text-white focus:outline-none focus:border-blue-500"
                            value={newRecordTitle}
                            onChange={e => setNewRecordTitle(e.target.value)}
                            placeholder="e.g. Q3_Financials.pdf"
                        />
                    </div>
                    <div>
                        <label className="block text-sm text-slate-400 mb-1">Data Source</label>
                        <select 
                            className="w-full bg-slate-900 border border-slate-700 rounded p-2 text-white focus:outline-none focus:border-blue-500"
                            value={newRecordSource}
                            onChange={(e: any) => setNewRecordSource(e.target.value)}
                        >
                            <option value="Local">Local Upload</option>
                            <option value="SharePoint">SharePoint</option>
                            <option value="OneDrive">OneDrive</option>
                        </select>
                    </div>
                    <div>
                         <label className="block text-sm text-slate-400 mb-1">Retention Schedule (Sentence)</label>
                        <select 
                            className="w-full bg-slate-900 border border-slate-700 rounded p-2 text-white focus:outline-none focus:border-blue-500"
                            value={newRecordSchedule}
                            onChange={(e: any) => setNewRecordSchedule(e.target.value)}
                        >
                            <option value="">-- Select Authority --</option>
                            {schedules.map(s => (
                                <option key={s.id} value={s.id}>{s.code} - {s.name} ({s.retentionYears} yrs)</option>
                            ))}
                        </select>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                        <div>
                            <label className="block text-sm text-slate-400 mb-1">File Type</label>
                            <select 
                                className="w-full bg-slate-900 border border-slate-700 rounded p-2 text-white focus:outline-none focus:border-blue-500"
                                value={newRecordType}
                                onChange={(e: any) => setNewRecordType(e.target.value)}
                            >
                                <option value="PDF">PDF</option>
                                <option value="DOCX">DOCX</option>
                            </select>
                        </div>
                        <div>
                            <label className="block text-sm text-slate-400 mb-1">Classification</label>
                            <select 
                                className="w-full bg-slate-900 border border-slate-700 rounded p-2 text-white focus:outline-none focus:border-blue-500"
                                value={newRecordClass}
                                onChange={(e: any) => setNewRecordClass(e.target.value)}
                            >
                                {Object.values(Classification).map(c => <option key={c} value={c}>{c}</option>)}
                            </select>
                        </div>
                    </div>
                </div>
                <div className="flex justify-end gap-3 mt-6">
                    <button 
                        onClick={() => setShowAddModal(false)}
                        className="px-4 py-2 text-slate-400 hover:text-white transition-colors"
                    >
                        Cancel
                    </button>
                    <button 
                        onClick={handleAddRecord}
                        className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded transition-colors"
                    >
                        Register
                    </button>
                </div>
            </div>
        </div>
      )}
    </div>
  );
};

export default RecordsRegistry;